export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          username: string;
          password: string;
          mobile_number: string | null;
          role: "admin" | "jobber" | "partner";
          status: "active" | "inactive";
          created_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email?: string;
          username: string;
          password: string;
          mobile_number?: string | null;
          role: "admin" | "jobber" | "partner";
          status?: "active" | "inactive";
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          username?: string;
          password?: string;
          mobile_number?: string | null;
          role?: "admin" | "jobber" | "partner";
          status?: "active" | "inactive";
          created_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          customer_name: string;
          mobile_number: string;
          city: string;
          address: string | null;
          residence_address: string | null;
          office_address: string | null;
          purpose_of_loan: string | null;
          loan_category: string;
          required_amount: string;
          cibil_score: string | null;
          purchase_value: string | null;
          sale_deed_amount: string | null;
          lead_source: string;
          assigned_to: string;
          status: string;
          notes: string;
          created_at: string;
          transferred_from: string | null;
          transferred_to: string | null;
          transfer_status: string | null;
        };
        Insert: {
          id?: string;
          customer_name: string;
          mobile_number: string;
          city: string;
          address?: string | null;
          residence_address?: string | null;
          office_address?: string | null;
          purpose_of_loan?: string | null;
          loan_category: string;
          required_amount?: string;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          lead_source?: string;
          assigned_to: string;
          status?: string;
          notes?: string;
          created_at?: string;
          transferred_from?: string | null;
          transferred_to?: string | null;
          transfer_status?: string | null;
        };
        Update: {
          id?: string;
          customer_name?: string;
          mobile_number?: string;
          city?: string;
          address?: string | null;
          residence_address?: string | null;
          office_address?: string | null;
          purpose_of_loan?: string | null;
          loan_category?: string;
          required_amount?: string;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          lead_source?: string;
          assigned_to?: string;
          status?: string;
          notes?: string;
          created_at?: string;
          transferred_from?: string | null;
          transferred_to?: string | null;
          transfer_status?: string | null;
        };
      };
      customers: {
        Row: {
          id: string;
          full_name: string;
          mobile_number: string;
          address: string;
          residence_address: string | null;
          office_address: string | null;
          pan_number: string;
          aadhaar_number: string;
          employment_type: string;
          monthly_income: string;
          existing_liabilities: string;
          assigned_to: string;
          notes: string;
          created_at: string;
          loan_category: string | null;
          purpose_of_loan: string | null;
          has_co_applicant: boolean | null;
          co_applicants: Json | null;
          cibil_score: string | null;
          purchase_value: string | null;
          sale_deed_amount: string | null;
          documents: Json | null;
          stored_files: Json | null;
          property_address: string | null;
          scheme_name: string | null;
          date_added: string | null;
        };
        Insert: {
          id?: string;
          full_name: string;
          mobile_number: string;
          address?: string;
          residence_address?: string | null;
          office_address?: string | null;
          pan_number?: string;
          aadhaar_number?: string;
          employment_type?: string;
          monthly_income?: string;
          existing_liabilities?: string;
          assigned_to: string;
          notes?: string;
          created_at?: string;
          loan_category?: string | null;
          purpose_of_loan?: string | null;
          has_co_applicant?: boolean | null;
          co_applicants?: Json | null;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          documents?: Json | null;
          stored_files?: Json | null;
          property_address?: string | null;
          scheme_name?: string | null;
          date_added?: string | null;
        };
        Update: {
          id?: string;
          full_name?: string;
          mobile_number?: string;
          address?: string;
          residence_address?: string | null;
          office_address?: string | null;
          pan_number?: string;
          aadhaar_number?: string;
          employment_type?: string;
          monthly_income?: string;
          existing_liabilities?: string;
          assigned_to?: string;
          notes?: string;
          created_at?: string;
          loan_category?: string | null;
          purpose_of_loan?: string | null;
          has_co_applicant?: boolean | null;
          co_applicants?: Json | null;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          documents?: Json | null;
          stored_files?: Json | null;
          property_address?: string | null;
          scheme_name?: string | null;
          date_added?: string | null;
        };
      };
      loan_applications: {
        Row: {
          id: string;
          customer_id: string;
          customer_name: string;
          mobile_number: string;
          address: string | null;
          residence_address: string | null;
          office_address: string | null;
          loan_category: string;
          purpose_of_loan: string | null;
          lender: string;
          requested_amount: string;
          approval_amount: string | null;
          disbursed_amount: string | null;
          interest_rate: string | null;
          tenure: string | null;
          emi_amount: string | null;
          cibil_score: string | null;
          purchase_value: string | null;
          sale_deed_amount: string | null;
          status: string;
          assigned_to: string;
          documents: Json | null;
          stored_files: Json | null;
          notes: string;
          created_at: string;
          application_number: string | null;
          submission_date: string | null;
          disbursement_date: string | null;
          rejection_reason: string | null;
          has_co_applicant: boolean | null;
          co_applicants: Json | null;
          property_address: string | null;
          scheme_name: string | null;
          completion_status: string | null;
        };
        Insert: {
          id?: string;
          customer_id?: string;
          customer_name?: string;
          mobile_number?: string;
          address?: string | null;
          residence_address?: string | null;
          office_address?: string | null;
          loan_category: string;
          purpose_of_loan?: string | null;
          lender: string;
          requested_amount: string;
          approval_amount?: string | null;
          disbursed_amount?: string | null;
          interest_rate?: string | null;
          tenure?: string | null;
          emi_amount?: string | null;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          status?: string;
          assigned_to: string;
          documents?: Json | null;
          stored_files?: Json | null;
          notes?: string;
          created_at?: string;
          application_number?: string | null;
          submission_date?: string | null;
          disbursement_date?: string | null;
          rejection_reason?: string | null;
          has_co_applicant?: boolean | null;
          co_applicants?: Json | null;
          property_address?: string | null;
          scheme_name?: string | null;
          completion_status?: string | null;
        };
        Update: {
          id?: string;
          customer_id?: string;
          customer_name?: string;
          mobile_number?: string;
          address?: string | null;
          residence_address?: string | null;
          office_address?: string | null;
          loan_category?: string;
          purpose_of_loan?: string | null;
          lender?: string;
          requested_amount?: string;
          approval_amount?: string | null;
          disbursed_amount?: string | null;
          interest_rate?: string | null;
          tenure?: string | null;
          emi_amount?: string | null;
          cibil_score?: string | null;
          purchase_value?: string | null;
          sale_deed_amount?: string | null;
          status?: string;
          assigned_to?: string;
          documents?: Json | null;
          stored_files?: Json | null;
          notes?: string;
          created_at?: string;
          application_number?: string | null;
          submission_date?: string | null;
          disbursement_date?: string | null;
          rejection_reason?: string | null;
          has_co_applicant?: boolean | null;
          co_applicants?: Json | null;
          property_address?: string | null;
          scheme_name?: string | null;
          completion_status?: string | null;
        };
      };
      follow_ups: {
        Row: {
          id: string;
          customer_name: string;
          mobile_number: string;
          address: string | null;
          purpose_of_loan: string | null;
          lead_id: string | null;
          application_id: string | null;
          type: string;
          notes: string;
          next_follow_up_date: string;
          next_follow_up_time: string;
          priority: string;
          status: string;
          assigned_to: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          mobile_number: string;
          address?: string | null;
          purpose_of_loan?: string | null;
          lead_id?: string | null;
          application_id?: string | null;
          type: string;
          notes?: string;
          next_follow_up_date: string;
          next_follow_up_time: string;
          priority?: string;
          status?: string;
          assigned_to: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          mobile_number?: string;
          address?: string | null;
          purpose_of_loan?: string | null;
          lead_id?: string | null;
          application_id?: string | null;
          type?: string;
          notes?: string;
          next_follow_up_date?: string;
          next_follow_up_time?: string;
          priority?: string;
          status?: string;
          assigned_to?: string;
          created_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_name: string;
          user_role: string;
          action: string;
          entity_type: string;
          entity_id: string;
          details: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_name: string;
          user_role: string;
          action: string;
          entity_type: string;
          entity_id: string;
          details?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_name?: string;
          user_role?: string;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          details?: string;
          created_at?: string;
        };
      };
      lenders: {
        Row: {
          id: string;
          name: string;
        };
        Insert: {
          id?: string;
          name: string;
        };
        Update: {
          id?: string;
          name?: string;
        };
      };
      sent_emails: {
        Row: {
          id: string;
          recipients: Json;
          subject: string;
          body: string;
          has_attachment: boolean;
          image_attachment: string | null;
          sent_at: string;
          sent_by: string;
        };
        Insert: {
          id?: string;
          recipients: Json;
          subject: string;
          body: string;
          has_attachment?: boolean;
          image_attachment?: string | null;
          sent_at?: string;
          sent_by: string;
        };
        Update: {
          id?: string;
          recipients?: Json;
          subject?: string;
          body?: string;
          has_attachment?: boolean;
          image_attachment?: string | null;
          sent_at?: string;
          sent_by?: string;
        };
      };
      sms_messages: {
        Row: {
          id: string;
          to_phone: string;
          to_name: string;
          message: string;
          sent_at: string;
          sent_by: string;
          status: string;
        };
        Insert: {
          id?: string;
          to_phone: string;
          to_name: string;
          message: string;
          sent_at?: string;
          sent_by: string;
          status?: string;
        };
        Update: {
          id?: string;
          to_phone?: string;
          to_name?: string;
          message?: string;
          sent_at?: string;
          sent_by?: string;
          status?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
